version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev:ba81ae537e722ad99906599f5d3ad367ca854433
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
